version: "3.7"
services:
   rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq-alpine"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=interface
    ports:
      - "5672:5672"
      - "15672:15672"
    command: rabbitmq-server
    user: "1000:1000"

volumes:
  rabbitmq_data:
  rabbitmq_logs: